config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
      member do
      get :following, :followers
      end
  end
  resources :posts
  resources :comments
  resources :notifications, only: [:update]
  resources :account_activations, only: [:edit]
  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, as: :notificationable

  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true

  scope :order_by_created_at, -> {order created_at: :desc}
  scope :load_data_post, ->{select("id, title, content, created_at, user_id").order created_at: :desc}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :find_post, only: [:show]
  before_action :correct_user, only: [:edit, :destroy, :update]

  def new
    @post = current_user.posts.build
  end

  def index
    @posts = Post.load_data_post.page(params[:page]).per Settings.post.per_page
  end

  def show
    @comments = @post.comments.all
    @comment = @post.comments.build
  end

  def edit; end

  def update
    if @post.update_attributes post_params
      flash[:success] = t ".susscess"
      redirect_to @post
    else
      render :edit
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = t ".susscess"
      redirect_to @post
    else
      render "static_pages/home"
    end
  end

  def destroy
    @post.destroy
    flash[:success] = t ".susscess"
    redirect_to current_user
  end

  def find_post
    @post = Post.find_by id: params[:id]
    return if @post
    flash.now[:danger] = t ".danger"
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def correct_user
    @post = current_user.posts.find_by id: params[:id]
    redirect_to root_url if @post.nil?
  end
end

app/views/posts/_comment_form.html.erb
<div id="comment-form">
  <h3>Comments (<%= @post.comments.count%>)</h3>
  <% @comments.each do |comment| %>
      <li>
        <%= link_to gravatar_for(comment.user, size: Settings.avar_comment.size), comment.user%>
        <span>
          <span class="user"><%= link_to comment.user.name, comment.user %></span>
          <span class="timestamp">
            <%= time_ago_in_words(comment.created_at)%> <%= t".ago" %>
          </span>
          <span>
            <% if current_user == comment.user %>
              <%= link_to t(".edit"), edit_comment_path(comment),
                remote: true %> /
              <%= link_to t(".delete"), comment_path(comment), method: :delete,
                remote: true, data: {confirm: t(".confirm")}%></p>
            <% end %>
          </span>
        </span>
        <span class="content"><p><%= comment.content %>
        <hr/>
      </li>
  <% end %>
  <%= render "comments/form" %>
</div>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="title_my_posts"><%= link_to post.title, post_path(post.id)%></span>
  <span class="timestamp">
    <%= t ".posted" %> <%= time_ago_in_words(post.created_at) %> <%= t ".ago" %>
  </span>
  <span class="comment"><%= post.comments.count%> comment<span>
</li>

app/views/posts/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control"%>

      <%= f.label :content %>
      <%= f.text_area :content, placeholder: t(".placeholder"), id: "markdown" %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>
<script>
  $(document).ready(function () {
    var simplemde = new SimpleMDE({ element: document.getElementById("markdown") });
  });
</script>

app/views/posts/edit.html.erb
<% provide :button_text, "Save Changes" %>
<div class="row">
  <h1> Create Post</h1>
  <aside class="col-md-12">
    <section class="post_form">
      <%= render "post_form" %>
    </section>
  </aside>
</div>

app/views/posts/index.html.erb
<h1><%= t ".title" %></h1>

<ul class="posts">
  <% @posts.each do |post| %>
    <li>
      <%= link_to gravatar_for(post.user, size: Settings.avar_index.size), post.user%>
      <span>
        <span class="user"><%= link_to post.user.name, post.user %> </span>
        <span class="timestamp">
          <%= t ".posted" %> <%= time_ago_in_words(post.created_at)%> <%= t ".ago" %>
        </span>
      </span>
      <span class="title"><%= link_to post.title, post_path(post.id)%></span>
      <span class="comment"><%= post.comments.count%> comment<span>
    </li>
  <% end %>
</ul>
<%= paginate @posts, theme: "twitter-bootstrap-3" %>

app/views/posts/new.html.erb
<% provide :button_text, "Create Post" %>
<div class="row">
  <h1><%= t ".title" %></h1>
  <aside class="col-md-12">
    <section class="post_form">
      <%= render "post_form" %>
    </section>
  </aside>
</div>

app/views/posts/show.html.erb
<div class="post-article markdown">
 <% if current_user?(@post.user) %>
    <%= link_to t(".edit"), edit_post_path(@post) %> /
    <%= link_to t(".delete"), @post, method: :delete,
      data: { confirm: "You sure?" } %>
  <% end %>
  <div>
    <h1><%= @post.title %></h1>
    <span>
      Author: <%= link_to @post.user.name, @post.user%>
      <br/>
      At: <%= @post.created_at.strftime("%H:%M %d/%m/%Y") %>
    </span>
    <hr/>
    <%= markdown @post.content %>
  </div>
</div>
<%= render "comment_form"%>